### ISSUE TITLE
UnicodeDecodeError in corpus.py

### ISSUE THREAD

**Issue by yuewang1402** [ne7ermore/deeping-flow#2]
Sorry, I have encountered a UnicodeDecodeError when I run the corpus.py with python3.6.
The problem is following:

Traceback (most recent call last):
  File "corpus.py", line 136, in <module>
    Corpus()
  File "corpus.py", line 69, in __init__
    self.parse_data("data/train.txt", True)
  File "corpus.py", line 75, in parse_data
    for line in open(inf):
  File "/home/guest/Users/Wangyue/virtualenv/tensorflow_py36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 513: invalid continuation byte

Can you help me to solve this problem? 
Thank you.

**Comment by ne7ermore** [comment]
which project
