### ISSUE TITLE
A error of deeping-flow/reinforced-translate

### ISSUE THREAD

**Issue by orazheng** [ne7ermore/deeping-flow#4]
hi, 
I tried to run deeping-flow/reinforced-translate/ but got an error:

Traceback (most recent call last):
  File "train.py", line 65, in <module>
    rl = Reinforced(model, args)
  File "/Users/zhengwenjia/Workspace/Temp/deeping-flow/reinforced-translate/model.py", line 176, in __init__
    mask = pad_mask(model.tgt, EOS, [args.batch_size, args.max_len])
NameError: name 'EOS' is not defined

**Comment by ne7ermore** [comment]
fixed, plz git pull again
